[package]
description = "Youless energy meter integration"
edition = "2021"
name = "connection-youless"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
prost = "0.12.3"
serde = { version = "1.0.195", default-features = false, features = ["derive"] }
toml = { version = "0.8.8", default-features = false, features = ["parse"] }
